project_id = "hmjmlqmwfarqlrhrkyla"

[functions.telegram-bot-webhook]
verify_jwt = false

[functions.process-emoji-tasks]
verify_jwt = false

[functions.scrape-source-members]
verify_jwt = false

[functions.telegram-sync-groups]
verify_jwt = false

[functions.validate-telegram-group]
verify_jwt = false

[functions.validate-telegram-sessions]
verify_jwt = false

[functions.process-member-invites]
verify_jwt = false

[functions.claim-emoji-task]
verify_jwt = false

[functions.request-health-check]
verify_jwt = true
